addSbtPlugin("com.geirsson"              % "sbt-ci-release" % "1.5.3")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"     % "5.6.0")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"    % "0.5.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.13")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"        % "0.3.7")
addSbtPlugin("ch.epfl.lamp"              % "sbt-dotty"      % "0.4.1")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.6.1")
